import { defineConfig } from 'tsup'

// One bundled ESM entry per importable subpath. esbuild inlines imported JSON
// and resolves the internal @firmware/@/@shared aliases from tsconfig `paths`.
// `splitting` dedupes shared code into chunks. Keys become the dist file paths,
// which the package.json `./*` wildcard export maps onto.
export default defineConfig({
    entry: {
        index: 'src/index.ts',
        builtins: 'src/builtins.ts',
        registry: 'src/registry.ts',
        service: 'src/service.ts',
        types: 'src/types.ts',
        codec: 'src/codec.ts',
        adapter: 'src/adapter.ts',
        configEditing: 'src/configEditing.ts',
        sideload: 'src/sideload.ts',
        hostEnv: 'src/hostEnv.ts',
        mouseCommands: 'src/mouseCommands.ts',
        legendIcons: 'src/legendIcons.ts',
        paramLabel: 'src/paramLabel.ts',
        lighting: 'src/lighting.ts',
        config: 'src/config/index.ts',
        catalog: 'src/catalog/index.ts',
        'catalog/types': 'src/catalog/types.ts',
        'catalog/pages': 'src/catalog/pages.ts',
        'clients/zmk': 'src/clients/zmk/index.ts',
        'clients/zmk/index': 'src/clients/zmk/index.ts',
        'clients/zmk/codec': 'src/clients/zmk/codec.ts',
        'clients/zmk/displayNameToBinding': 'src/clients/zmk/displayNameToBinding.ts',
        'clients/zmk/parseCombos': 'src/clients/zmk/parseCombos.ts',
        'clients/zmk/paramLabel': 'src/clients/zmk/paramLabel.ts',
        'clients/qmk': 'src/clients/qmk/index.ts',
        'clients/qmk/codec': 'src/clients/qmk/codec.ts',
        'clients/qmk/layoutSideload': 'src/clients/qmk/layoutSideload.ts',
        'clients/qmk/viaRegistry': 'src/clients/qmk/viaRegistry.ts',
        'clients/qmk-vial': 'src/clients/qmk-vial/index.ts',
        'clients/keychron': 'src/clients/keychron/index.ts',
        'clients/mock': 'src/clients/mock/index.ts',
        'clients/mock/codec': 'src/clients/mock/codec.ts',
        'clients/mock/service': 'src/clients/mock/service.ts',
        'clients/remappr': 'src/clients/remappr/index.ts',
        'clients/remappr/protocol': 'src/clients/remappr/protocol.ts',
        'clients/remappr/auth': 'src/clients/remappr/auth.ts',
        'clients/remappr/actions': 'src/clients/remappr/actions.ts',
        'clients/via/lightingMenu': 'src/clients/via/lightingMenu.ts',
    },
    format: ['esm'],
    target: 'es2022',
    platform: 'neutral',
    splitting: true,
    dts: true,
    clean: true,
    sourcemap: true,
    treeshake: true,
    // Copy raw .json (catalog hid-pages, usage tables, seed) into dist so the
    // `./*.json` export resolves for consumers importing them directly.
    onSuccess:
        "rsync -a --prune-empty-dirs --include='*/' --include='*.json' --exclude='*' src/ dist/",
})
