// Pattern check: no GoF pattern (-) — rejected — pure keymap.c emitter; string template generation from neutral Keymap.
// QMK keymap.c emitter — generates a `keymaps[][MATRIX_ROWS][MATRIX_COLS]`
// table. Cells use the shared symbolic keycode emitter (qmkBindingCode);
// keycodes outside its table fall through to raw 0xNNNN literals.

import type { ExportedFile, Keymap } from '@firmware/types'
import { qmkBindingCode } from './actions'

export function emitKeymapC(keymap: Keymap, deviceName: string): string {
    const lines: string[] = []
    lines.push(`// Generated by Remappr — VIA layout export`)
    lines.push(`// Device: ${deviceName}`)
    lines.push(`// Layers: ${keymap.layers.length}`)
    lines.push(``)
    lines.push(`#include QMK_KEYBOARD_H`)
    lines.push(``)
    lines.push(`const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {`)
    keymap.layers.forEach((layer, idx) => {
        const cells = layer.keys.map((k) => qmkBindingCode(k.kind, k.params))
        const wrapped: string[] = []
        for (let i = 0; i < cells.length; i += 8) {
            wrapped.push('        ' + cells.slice(i, i + 8).join(', '))
        }
        lines.push(`    [${idx}] = LAYOUT( // ${layer.name}`)
        lines.push(wrapped.join(',\n'))
        lines.push(`    ),`)
    })
    lines.push(`};`)
    lines.push(``)
    return lines.join('\n')
}

export function exportKeymap(
    keymap: Keymap,
    deviceName: string,
): ExportedFile[] {
    return [
        {
            filename: 'keymap.c',
            mime: 'text/x-c',
            content: emitKeymapC(keymap, deviceName),
        },
    ]
}
